### ISSUE TITLE
output and packageName configuration not working

### ISSUE THREAD

**Issue by RaymondHsu** [valery1707/kaitai-maven-plugin#20]
maven plugin configuration:

<output>${project.basedir}/src/main/java</output>
<packageName>com.mycomp.prod.parser</packageName>

the plugin always create an extra directory "src"  in the front.  The above will put the generated java file in ${project.basedir}/src/main/java/src/com/mycomp/prod/parser/ directory

**Comment by valery1707** [comment]
Configuration parameters `output` and `packageName` is working. And you see it.

But you are right: directory `src` is always created between `output` and `packageName`.
But this directory created by [Kaitai compiler itself](https://github.com/kaitai-io/kaitai_struct_compiler/blob/38860dbbf77748aae139d05551b5752620a9e515/shared/src/main/scala/io/kaitai/struct/languages/JavaCompiler.scala#L46) and not by this plugin.

**Comment by RaymondHsu** [comment]
Thanks.  I see it now.   The extra "src" make the output parameter not useful to integrate with maven build process.  I need to copy the generated files to destination manually every time (or need to modify pom.xml to do the copy for me)

**Comment by valery1707** [comment]
@RaymondHsu I am thinking about a new parameter (for example, "eliminateSrc" or "directOutput") for allow to remove "src" from the final path.
