### ISSUE TITLE
Test environment is broken

### ISSUE THREAD

**Issue by SergeyLukashevich** [valery1707/kaitai-maven-plugin#24]
Travis CI reports about errors that not related with a feture request:

```The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .```

and 

```The command "eval mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V " failed 3 times.```

For more details see PR #23

**Comment by valery1707** [comment]
Seems that OracleJDK 8 not supported any more.
